AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  imaging-api
  
  Sample SAM Template for imaging-api

Globals:
  Api:
    BinaryMediaTypes:
    - image~1png
  Function:
    Timeout: 15
    MemorySize: 256

Resources:
  DistFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: dist/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /dist
            Method: GET
            RequestParameters:
              - method.request.querystring.myqueryparam:
                  Required: true
Outputs:
  DistAPI:
    Description: "API Gateway endpoint URL for Prod environment for Dist Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/dist/"
  DistFunction:
    Description: "Dist Lambda Function ARN"
    Value: !GetAtt DistFunction.Arn
  DistFunctionIamRole:
    Description: "Implicit IAM Role created for Dist function"
    Value: !GetAtt DistFunctionRole.Arn